### ISSUE TITLE
ProcessConfig.initialise raises TypeLoadException

### ISSUE THREAD

**Issue by StefanBertels** [louthy/echo-process#2] opened 2017-03-09 11:15 UTC
Hi Paul,

I'm just trying out new echo-process. I try to build a small local actor system.

If I call `ProcessConfig.initialise();` in Main (console-app), I get a runtime exception:

`System.TypeLoadException: 'Could not load type '___ParserExt' from assembly 'LanguageExt.Parsec, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.'`

```
  <package id="Echo.Process" version="2.0.2-alpha" targetFramework="net452" />
  <package id="LanguageExt.Core" version="2.0.26-beta" targetFramework="net452" />
  <package id="LanguageExt.Parsec" version="2.0.26-beta" targetFramework="net452" />

```

I tried using some older LanguageExt (alpha-15) because that is used in echo-process (source code) but this results in another exception (ArgumentNullException).

**Comment by louthy** [comment] 2017-03-09 17:42
@StefanBertels Hi Stefan, I'll take a look.

**Comment by louthy** [comment] 2017-03-09 18:25
@StefanBertels Get 2.0.4-alpha.  I think you may have got the latest LanguageExt, which has incompatible types (like `__ParserExt` is now `ParserExtensions`).  Anyway, I've just updated the references and check it all runs.

**Comment by StefanBertels** [comment] 2017-03-10 00:22
Thanks a lot! Runtime error is gone, but does not fly yet.
```
class Program
    {
        private class MyState : IDisposable
        {
            public void Dispose()
            {
                Console.WriteLine("disposed mystate");
            }
        }

        static void Main(string[] args)
        {
            ProcessConfig.initialise();

            var pid = spawn<Option<MyState>, string>("watcher", () =>
            {
                Console.WriteLine("Setup process");
                return None;
            }
            , (state, msg) =>
            {
                Console.WriteLine("Received " + msg);
                return state;
            });

            Console.WriteLine("process spawned");

            pid.Tell("hello world");

            shutdownAll();

            Console.WriteLine("end, press key.");
            Console.ReadKey();

        }
    }
```

Actor isn't called (tell returns without Console output).

Process.Exists(pid) says: true.

Is my setup wrong?

**Comment by louthy** [comment] 2017-03-10 01:48
It's correct, there was a race condition that meant your message was sent before the process' queue had spawned.  Get the latest from nu-get and it should work.

Definitely be very cautious of using this library right now.  It's had a tiny amount of testing since I rewrote the core of language-ext, and will definitely have some problems.  The main reason I've released the alpha is so I can easily drop it into my personal projects to test.

**Comment by StefanBertels** [comment] 2017-03-10 07:44
Thank you for fixing this, too. I will try out.

I'm aware that there will be more bugs and I start by looking into the source code. Are you ready to get more feedback (i.e. reported issues) to get this more stable soon? Do you have a time line for this project (beta status)?

**Comment by louthy** [comment] 2017-03-10 12:09
@StefanBertels I'm always interested in bugs.  They will always need fixing :)

The Process system is something I use in production in a very large app (with many services), so on the whole it should be good.  But the live version I'm running right now is pre-v2.  

My plan is to get all of the unit tests that were in the old project back in, and get running all of the samples that were in the old project.  I have been re-writing the ProcessJS feature to use WebSockets rather than SignalR, and there's still some features missing from that (and it doesn't tear down sessions at the moment).

Then I will be adding it to my production app, which is my best 'test bed'.  And then I'll consider pushing it to beta.

I am seriously busy at the moment, so this could take 1 - 2 months.

**Comment by StefanBertels** [comment] 2017-03-10 19:17
Thanks for pointing out. I'm happy with this. If I find problems, I will report them.

One general/design question: As far as I can see actors have a handler function and can have a setup function. I want to use the latter to allocate ressources (maybe locking something).

Seems there is no teardown function, so at least explicit shutdown() would not release ressources (before returning). That might be a problem when e.g. restarting processes.

What's your opinion on this? Feature could be implicit by checking State type for IDisposable interface and disposing on shutdown.

**Comment by louthy** [comment] 2017-03-10 19:44
If your state (that you return from the setup function, and that you maintain for the life of the process) implements IDisposable then it will be disposed on shutdown or if you Process.kill the process.

**Comment by StefanBertels** [comment] 2017-03-15 07:33
2.0.6-alpha seems to call setup method twice:

private static void SimpleTest()
        {
            var pid = spawn<Option<DateTime>, string>("watcher", () =>
            {
                Console.WriteLine("Setup process");
                return None;
            }
            , (state, msg) =>
            {
                Console.WriteLine("Received " + msg);
                return DateTime.UtcNow;
            });

            Console.WriteLine($"process {pid} spawned");

            pid.Tell("hello world");
        }

        static void Main(string[] args)
        {
            ProcessConfig.initialise();

            SimpleTest();

            Console.ReadKey();

            shutdownAll();

            Console.WriteLine("end, press key.");
            Console.ReadKey();

        }

**Comment by StefanBertels** [comment] 2017-03-15 09:16
(setup twice problem => #5)

I dont' get MyState.Dispose() called on shutdownAll (with MyState implementing IDiposable).

**Comment by louthy** [comment] 2017-03-23 23:57
> I dont' get MyState.Dispose() called on shutdownAll or pid.Kill

`kill(pid)` seems to work for me.  There was an issue with `shutdownAll` caused by the new struct Map type in lang-ext, which is now fixed.

This is the test app I used:
```c#
    public interface IMyState : IDisposable
    {
        void Add(int num);
        void Remove(int num);
        void Show();

    }
    class Program
    {
        static void Main(string[] args)
        {
            ProcessConfig.initialise();

            var pid = ProxyTest();

            Console.ReadKey();
            Console.WriteLine("done.  next to kill process... press a key");
            Console.ReadKey();

            kill(pid);

            Console.WriteLine("process is killed.  next to shutdown... press a key");
            Console.ReadKey();

            shutdownAll();

            Console.WriteLine("done.  any key to quit.");
            Console.ReadKey();
        }

        public class MyState : IMyState
        {
            HashSet<int> state = HashSet<int>();

            public MyState()
            {
                Console.WriteLine("Setup called");
            }

            public void Add(int num)
            {
                Console.WriteLine($"add {num}...");
                state = state.Add(num);
            }

            public void Dispose()
            {
                Console.WriteLine($"Dispose");
            }

            public void Remove(int num)
            {
                Console.WriteLine($"Remove {num}...");
                state = state.Remove(num);
            }

            public void Show()
            {
                Console.WriteLine("content: " + string.Join(",", state));
            }
        }

        private static ProcessId ProxyTest()
        {
            ProcessId pid = spawn<MyState>("mystate");

            var state = proxy<IMyState>(pid);

            state.Add(5);
            state.Add(3);
            state.Show();
            state.Remove(5);
            state.Show();

            return pid;
        }
    }
```

**Comment by louthy** [comment] 2017-03-23 23:58
The fix is in `v2.0.9`

**Comment by StefanBertels** [comment] 2017-03-24 11:16
Thanks for fixing, works in a non-proxy process, too.

One note: does not work in my example above because Option<T> does not implement IDisposable so Dispose() of T is not called. See [language-ext issue 205](https://github.com/louthy/language-ext/issues/205).

I noticed that calling shutdownAll will dispose synchronously but kill won't.

**Comment by louthy** [comment] 2017-03-24 17:42
@StefanBertels I have commented on why `Option` can't implement `IDisposable` in the lang-ext issue.

> I noticed that calling shutdownAll will dispose synchronously but kill won't.

Indeed.  `shutdownAll` is the end-of-life for the whole Process system.  And so it blocks.  `kill` is a regular part of the actor system, and is actioned by sending a `ShutdownProcess` message to the Process.

**Closed** 2017-07-10 16:17 UTC
